
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLModel_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLModel.ModelInput sampleData = new MLModel.ModelInput()
            {
                ImageSource = @"C:\Examples\HackathonPOC\ImageProcessingApp\BrainTumar\brain_tumor_dataset\no\1 no.jpeg",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");


            Console.WriteLine($"ImageSource: {@"C:\Examples\HackathonPOC\ImageProcessingApp\BrainTumar\brain_tumor_dataset\no\1 no.jpeg"}");


            Console.WriteLine($"\n\nPredicted Label value: {predictionResult.Prediction} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
